FROM node:12.19-alpine

# APP
ARG PORT
ARG DEBUG_PORT

# DB
ARG DB_HOST
ARG DB_PORT
ARG DB_USERNAME
ARG DB_PASSWORD
ARG DB_NAME

# SERVICES
ARG SERVICE_ORDER_RMQ_URL
ARG SERVICE_ORDER_RMQ_QUEUE
ARG SERVICE_PAYMENT_RMQ_URL
ARG SERVICE_PAYMENT_RMQ_QUEUE
ARG DELIVERY_SECOND_DELAY

ENV NODE_ENV development
ENV PORT $PORT
ENV DEBUG_PORT $DEBUG_PORT
ENV DB_HOST $DB_HOST
ENV DB_PORT $DB_PORT
ENV DB_USERNAME $DB_USERNAME
ENV DB_PASSWORD $DB_PASSWORD
ENV DB_NAME $DB_NAME
ENV SERVICE_ORDER_RMQ_URL $SERVICE_ORDER_RMQ_URL
ENV SERVICE_ORDER_RMQ_QUEUE $SERVICE_ORDER_RMQ_QUEUE
ENV SERVICE_PAYMENT_RMQ_URL $SERVICE_PAYMENT_RMQ_URL
ENV SERVICE_PAYMENT_RMQ_QUEUE $SERVICE_PAYMENT_RMQ_QUEUE
ENV DELIVERY_SECOND_DELAY $DELIVERY_SECOND_DELAY

WORKDIR /usr/src/app

RUN apk update
RUN apk add g++ make python
RUN apk add git bash

COPY package*.json ./

# add yarn
RUN npm i yarn@latest -g --force

RUN yarn install

COPY . .

RUN yarn run build

ENTRYPOINT [ "bash", "./init.sh" ]